// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ListController from "./list_controller"
application.register("list", ListController)

import NextController from "./next_controller"
application.register("next", NextController)
