// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import InstaPostController from "./insta_post_controller"
application.register("insta-post", InstaPostController)

import ListController from "./list_controller"
application.register("list", ListController)
