// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddNewProfileController from "./add_new_profile_controller"
application.register("add-new-profile", AddNewProfileController)

import ListController from "./list_controller"
application.register("list", ListController)
